var logos = {
		'AIoTV(视九TVbox)' : '<img src="images/logos/ShijuiTV.png" class="logo">',
		'Antpool-ELA' : '<img src="images/logos/Antpool.png" class="logo">',
		'AnyPeer' : '<img src="images/logos/AnyPeer3.png" class="logo">',
		'BIT.GAME' : '<img src="images/logos/BIT.GAME.png" class="logo">',
		'BitWork (CR Region HK)' : '<img src="images/logos/BitWork.png" class="logo">',
		'Black Swan' : '<img src="images/logos/Black-Swan1.png" class="logo">',
		'BTC.com' : '<img src="images/logos/BTC1.png" class="logo">',
		'Cheery Community' : '<img src="images/logos/CheeryCommunity1_min.png" class="logo">',
		'CR Herald | CR 先锋资讯' : '<img src="images/logos/CR Herald.png" class="logo">',
		'Cyber Republic Press CR新闻团队' : '<img src="images/logos/Cyber Republic Press3_min.png" class="logo">',
		'CR Regions Global Fund - Clarence Liu' : '<img src="images/logos/Cyber Republic Regions.png" class="logo">',
		'DACA区块链技术公开课' : '<img src="images/logos/DACA.png" class="logo">',
		'DHG(大黄哥)' : '<img src="images/logos/DHG2.png" class="logo">',
		'ELA News (ELA新闻)' : '<img src="images/logos/ELA News2.png" class="logo">',
		'ElaChat' : '<img src="images/logos/ELAChat.png" class="logo">',
		'elafans' : '<img src="images/logos/ELA Fans.png" class="logo">',
		'ELAFISH' : '<img src="images/logos/ELAFISH_1.png" class="logo">',
		'elaHorse @ 亦乐马' : '<img src="images/logos/ELAHORSE1.png" class="logo">',
		'ELAONSEN 亦来温泉' : '<img src="images/logos/elaonsen1.png" class="logo">',
		'Elastos Australia' : '<img src="images/logos/Elastos Australia1.png" class="logo">',
		'Elastos Carrier' : '<img src="images/logos/Carrier.png" class="logo">',
		'Elastos HIVE' : '<img src="images/logos/Hive.png" class="logo">',
		'Elastos Forest Node (EFN)' : '<img src="images/logos/Elaforestnode.png" class="logo">',
		'Elastos Scandinavia' : '<img src="images/logos/Scandinavia.png" class="logo">',
		'ElastosDMA' : '<img src="images/logos/DMA2.png" class="logo">',
		'Elate.ch' : '<img src="images/logos/ELATE.CH.png" class="logo">',
		'Elephant Wallet' : '<img src="images/logos/Elephant Wallet.png" class="logo">',
		'Enter Elastos - Ganymede' : '<img src="images/logos/Enter Elastos.png" class="logo">',
		'Enter Elastos - Titan ' : '<img src="images/logos/Enter Elastos.png" class="logo">',
		'Enter Elastos -Callisto' : '<img src="images/logos/Enter Elastos.png" class="logo">',
		'F2Pool' : '<img src="images/logos/F2Pool.png" class="logo">',
		'greengang' : '<img src="images/logos/Greengang1.png" class="logo">',
		'HashWorld' : '<img src="images/logos/HashWorld.png" class="logo">',
		'Hyper' : '<img src="images/logos/hyperim-logo.png" class="logo">',
		'IOEX(ioeX Network)' : '<img src="images/logos/ioeX2.png" class="logo">',
		'KuCoin' : '<img src="images/logos/KuCoin.png" class="logo">',
		'NextGenius' : '<img src="images/logos/Next Genius.png" class="logo">',
		'Noderators - Champagne' : '<img src="images/logos/Noderators.png" class="logo">',
		'Noderators - Watermelon' : '<img src="images/logos/Noderators.png" class="logo">',
		'Northern Lights' : '<img src="images/logos/Northern Lights.png" class="logo">',
		'Quantum Wealth Supernode' : '<img src="images/logos/Quantum Wealth Supernode.png" class="logo">',
    'RUOLAN(若兰)' : '<img src="images/logos/Roulon1.png" class="logo">',
		'Starfish' : '<img src="images/logos/Starfish.png" class="logo">',
		'ThaiEla' : '<img src="images/logos/ThaiELA.png" class="logo">',
		'The Houston Supernode' : '<img src="images/logos/Houston-Supernode2_min.png" class="logo">',
		'TYROLEE(小黑狼)' : '<img src="images/logos/TyroLee.png" class="logo">',
		'viewchain' : '<img src="images/logos/viewchain.png" class="logo">',
		'WeFilmchain' : '<img src="images/logos/wefilmchain.png" class="logo">',
		'Wild Strawberries Apollo' : '<img src="images/logos/Wild Strawberries - Apollo.png" class="logo">',
		'Wild Strawberries Atlas' : '<img src="images/logos/Wild Strawberries - Atlas.png" class="logo">',
		'Wild Strawberries Calypso' : '<img src="images/logos/Wild Strawberries - Calypso.png" class="logo">',
		'Witzer（无智）' : '<img src="images/logos/Witzer1.png" class="logo">',
		'YDiot(云端物联）' : '<img src="images/logos/YDiot.png" class="logo">',
		'曲率区动' : '<img src="images/logos/Curvature_Zone.png" class="logo">',
		'比特头条BITETT ' : '<img src="images/logos/Bitett.png" class="logo">',
		'链世界' : '<img src="images/logos/Blockchain_World_1.png" class="logo">',
		'韩锋/SunnyFengHan' : '<img src="images/logos/Sunny_Feng_Han_min.png" class="logo">',
		'区块链研习社' : '<img src="images/logos/Chainclub.png" class="logo">',
};
